version: '3'
services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres_container"
    ports:
      - 5433:5432
    volumes:
      - data:/zlagoda/db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: zlagoda

volumes:
  data: